# SpawnStack is a plugin that allows users to stack spawners and collect souls.
# Copyright (C) 2018 Kimberly Boynton
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# To request information, make an issue on the github page for this
# plugin.

###############################################
#           Spawn Stack Configuration         #
###############################################

soulitem:
  material: GHAST_TEAR
  durability: 0
  title: Soul Item
  lore:
    - soul item dummy field
  #A number between 0 and 1, decimal.
  dropchance: 1.3

spawner_default_delay: 200

database:
  enable: false
  url: pandette.net
  user: minecraft
  password: ReallyStronkPassword
  database: super_cool_db
  useSSL: false

messages:
  not_enough_souls: '&4You do not have enough souls for this spawner!'
  paid_souls: '&aYou have upgraded this spawner to level {level}!'
  too_low_delay: '&4This spawner can no longer be upgraded!'

soulcost:
  BAT: 1
  SKELETON: 2
